os: Visual Studio 2017

environment:
  CLI_VERSION: 2.0.0

install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/Syrx/Syrx.Databases/master/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info  
  - ps: dotnet restore
  - ps: dotnet build .\Syrx.Databases.sln
  - ps: Pop-Location

test_script:
    - ps: dotnet test .\Tests\Syrx.Connectors.Databases.Unit.Tests\Syrx.Connectors.Databases.Unit.Tests.csproj
    - ps: dotnet test .\Tests\Syrx.Readers.Databases.Unit.Tests\Syrx.Readers.Databases.Unit.Tests.csproj
    - ps: dotnet test .\Tests\Syrx.Settings.Databases.Unit.Tests\Syrx.Settings.Databases.Unit.Tests.csproj
    - ps: dotnet test .\Tests\Syrx.Settings.Databases.Serialization.Integration.Tests\Syrx.Settings.Databases.Serialization.Integration.Tests.csproj
version: 1.0.0.{build}
